apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: mvn-build-number-test-
spec:
  taskRef:
    name: set-build-version
  workspaces:
  - name: maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc
  - name: maven-source
    persistentVolumeClaim:
      claimName: maven-source-pvc
  # inputs:
  #   # NOTE: You need to have first git cloned into the maven-source workspace for this to work
  #   params:
  #   - name: GOALS
  #     value:
  #     - deploy
  #     - -DskipTests=true
  #     - -DaltDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-releases/
  #     - -DaltSnapshotDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-snapshots/
  #   - name: MAVEN_SETTINGS_CONFIGMAP
  #     value: custom-maven-settings
