apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: s2i-tomcat-8-run-
spec:
  inputs:
    params:
      - name: TLSVERIFY
        value: 'false'
      - name: MAVEN_MIRROR_URL
        value: 'http://nexus:8081/repository/maven-public/'
      - name: MAVEN_ARGS_APPEND
        value: '-PHSQLDB'
    resources:
      - name: source
        resourceRef:
          name: petclinic-git
  outputs:
    resources:
      - name: image
        paths:
          - build-image/image
        resourceRef:
          name: petclinic-image
  serviceAccountName: pipeline
  taskRef:
    kind: Task
    name: s2i-tomcat-8
  timeout: 1h0m0s