apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-git
spec:
  params:
  - name: url
    value: https://github.com/hatmarch/spring-framework-petclinic.git
  - name: revision
    value: trigger-test
  type: git
