apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-git
spec:
  params:
  - name: url
    value: http://gogs:3000/gogs/spring-petclinic.git
  - name: revision
    value: spring-5.2.0
  type: git
