apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: petclinic-dev-pipeline-tomcat-workspace
spec:
  workspaces:
  - name: local-maven-source
  - name: local-maven-repo
  params:
    - default: 'http://nexus:8081/repository/maven-public/'
      description: For local mvn files for build
      name: MAVEN_MIRROR_URL
      type: string
    - name: GIT_REPO
      type: string
      description: The repo to check output
      default: 'http://gogs:3000/gogs/spring-petclinic.git'
    - name: GIT_REVISION
      type: string
      description: The branch to be built
      default: 'spring-5.2.0'
    - name: GIT_MESSAGE
      type: string
      description: The commit message of the triggered build (if any)
      default: "<none>"
  resources:
  - name: app-image
    type: image
  tasks:
  - name: checkout
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: local-maven-source
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: message
      value: $(params.GIT_MESSAGE)
    # by setting subdirectory parameters to ""
    # checkout will clone to the root of the local-maven-source
    # volume, which will allow other tasks to find this directory
    # at their name for the mount point
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
  - name: set-build-version
    taskRef:
      name: set-build-version
    runAfter:
      - checkout
    workspaces:
    - name: maven-source
      workspace: local-maven-source
    - name: maven-repo
      workspace: local-maven-repo
  - name: build-app
    taskRef:
      name: maven-workspace
    runAfter:
      - set-build-version
    workspaces:
    - name: maven-source
      workspace: local-maven-source
    - name: maven-repo
      workspace: local-maven-repo
    params:
    - name: GOALS
      value:
      - install
      - -DskipTests
    - name: MAVEN_SETTINGS_CONFIGMAP
      value: custom-maven-settings
    - name: TARGET_DIR
      value: target
  - name: unit-tests
    taskRef:
      name: maven-workspace
    runAfter:
      - build-app
    retries: 3
    workspaces:
    - name: maven-source
      workspace: local-maven-source
    - name: maven-repo
      workspace: local-maven-repo
    params:
    - name: GOALS
      value:
      - surefire-report:report
      - site-deploy
    - name: MAVEN_SETTINGS_CONFIGMAP
      value: custom-maven-settings
  - name: build-image
    taskRef:
      name: s2i-tomcat-8-workspace
    runAfter:
      - unit-tests
      - code-analysis
    retries: 3
    params:
    - name: TLSVERIFY
      value: "false"
    - name: MAVEN_MIRROR_URL
      value: $(params.MAVEN_MIRROR_URL)
    - name: MAVEN_ARGS_APPEND
      value: "-Popenshift"
    - name: IMAGE_TAG
      value: $(tasks.set-build-version.results.build-number)
    # pointing to the target directory of a pre-built workspace will trigger a (faster) binary S2I build
    - name: PATH_CONTEXT
      value: target
    resources:
      outputs:
      - name: image
        resource: app-image
    workspaces:
    - name: maven-source
      workspace: local-maven-source
  - name: release-app
    taskRef:
      name: maven-workspace
    runAfter:
      - unit-tests
      - code-analysis
    # until parallel tasks that share a workspace can be scheduled to the same pod, 
    # we need to retry this task to try to get it to work.  This feature should be added
    # in an upcoming release of Tekton, see: https://github.com/tektoncd/pipeline/issues/2586
    retries: 3
    workspaces:
    - name: maven-source
      workspace: local-maven-source
    - name: maven-repo
      workspace: local-maven-repo
    params:
    - name: GOALS
      value:
      - deploy
      - -DskipTests=true
      - -DaltDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-releases/
      - -DaltSnapshotDeploymentRepository=nexus::default::http://nexus:8081/repository/maven-snapshots/
    - name: MAVEN_SETTINGS_CONFIGMAP
      value: custom-maven-settings
  - name: code-analysis
    taskRef:
      name: sonar
    runAfter:
      - build-app
    retries: 3
    workspaces:
    - name: maven-source
      workspace: local-maven-source
    - name: maven-repo
      workspace: local-maven-repo
    params:
    - name: MAVEN_SETTINGS_CONFIGMAP
      value: custom-maven-settings
    - name: MAVEN_PARAMETERS
      value:
      - -Dsonar.projectName="Spring Framework Petclinic"
  - name: deploy-dev
    taskRef:
      name: openshift-client
    runAfter:
      - build-image
      - release-app
    params:
    - name: COMMANDS
      value: |
          echo "Deploying latest image of petclinic to demo-dev"
          oc set image dc/petclinic petclinic="$(tasks.build-image.results.pushed-image-tag)" -n demo-dev
          oc rollout latest dc/petclinic -n demo-dev

          echo "Waiting for deployment to complete"
          oc rollout status dc/petclinic -n demo-dev
  - name: prompt-stage
    taskRef:
      name: prompt-slack
    runAfter:
      - deploy-dev
    params:
    - name: webhook-secret
      value: slack-webhook-secret
    - name: message-payload-configmap
      value: slack-message-payload
    - name: callback-payload
      value: $(tasks.set-build-version.results.build-number)
   