apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: petclinic-dev-pipeline-tomcat-
spec:
  pipelineRef:
    name: petclinic-dev-pipeline-tomcat-workspace
#  limitRangeName: "limit-mem-cpu-per-container"
  resources:
  - name: app-image
    resourceRef:
      name: petclinic-image
  workspaces:
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc
  - name: local-maven-source
    persistentVolumeClaim:
      claimName: maven-source-pvc