apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: petclinic-dev-pipeline-tomcat-
spec:
  pipelineRef:
    name: petclinic-dev-pipeline-tomcat-workspace
  resources:
  - name: app-image
    resourceRef:
      name: petclinic-image
  workspaces:
  - name: local-maven-source
    persistentVolumeClaim:
      claimName: maven-source-pvc