---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonar
spec:
  workspaces:
  - name: maven-source
  - name: maven-repo
    description: Where the maven artefacts are stored
  params:
  - name: SONAR_URL
    description: The SonarQube url
    type: string
    default: http://sonarqube:9000
  - name: MAVEN_SETTINGS_CONFIGMAP
    description: The configmap containing Maven settings.xml
    type: string
    default: maven-settings
  - name: MAVEN_PARAMETERS
    description: Additional maven parameters
    type: array
    default: []
  steps:
    - name: mvn
# NOTE: Cloud builder images are updated all the time.  This is pegged to a version of the cloud builder but if this version ever disappears
# From the registry, this command can be used instead with "./mvnw" as the command
#      image: quay.io/mhildenb/jboss-webserver31-tomcat8-openshift-base:1.0
      image: gcr.io/cloud-builders/mvn@sha256:15f5ce4d096ec336be3dbada0b0901bbfd92fb8760bb67bcc933da08faf231ed
      workingDir: $(workspaces.maven-source.path)
      command: [/usr/bin/mvn]
      args:
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - -Dsonar.host.url=$(params.SONAR_URL)
        - -Dsonar.userHome=/tmp/sonar
        - -DskipTests
        - -s
        - /var/config/settings.xml
        - install
        - sonar:sonar
        - $(params.MAVEN_PARAMETERS)
      volumeMounts:
        - name: maven-settings
          mountPath: /var/config
  volumes:
    - name: maven-settings
      configMap:
        name: $(params.MAVEN_SETTINGS_CONFIGMAP)