---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: sonar
spec:
  workspaces:
  - name: maven-source
  - name: maven-repo
    description: Where the maven artefacts are stored
  inputs:
    params:
    - name: SONAR_URL
      description: The SonarQube url
      type: string
      default: http://sonarqube:9000
    - name: MAVEN_SETTINGS_CONFIGMAP
      description: The configmap containing Maven settings.xml
      type: string
      default: maven-settings
  steps:
    - name: mvn
      image: gcr.io/cloud-builders/mvn
      workingDir: $(workspaces.maven-source.path)
      command: ["/usr/bin/mvn"]
      args:
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - -s
        - /var/config/settings.xml
        - install
        - sonar:sonar
        - -Dsonar.host.url=$(inputs.params.SONAR_URL)
        - -Dsonar.userHome=/tmp/sonar
        - -DskipTests
      volumeMounts:
        - name: maven-settings
          mountPath: /var/config
  volumes:
    - name: maven-settings
      configMap:
        name: $(inputs.params.MAVEN_SETTINGS_CONFIGMAP)