---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook-github
spec:
  serviceAccountName: pipeline
  triggers:
    - name: petclinic-webhook-github
      binding:
        name: github-triggerbinding
      template:
        name: petclinic-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook-github
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: webhook-github
spec:
  port:
    targetPort: 8080
  to:
    kind: "Service"
    name: el-webhook-github
    weight: 100
