---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gogs-triggerbinding
spec:
  params:
  - name: gitrevision
    value: $(body.after)
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)
  - name: contenttype
    value: $(header.Content-Type)
  - name: message
    value: $(body.commits[0].message)
