---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: petclinic-trigger-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: petclinic-dev-pipeline-tomcat-run-
      labels:
        tekton.dev/pipeline: petclinic-dev-pipeline-tomcat
    spec:
      pipelineRef:
        name: petclinic-dev-pipeline-tomcat
      resources:
      - name: app-git
        resourceSpec:
          type: git
          params:
          - name: url
            value: $(params.gitrepositoryurl)
          - name: revision
            value: $(params.gitrevision)
      - name: app-image
        resourceRef:
          name: petclinic-image
      workspaces:
      - name: local-maven-repo
        persistentVolumeClaim:
          claimName: maven-repo-pvc