---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: petclinic-trigger-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: petclinic-dev-pipeline-tomcat-workspace-triggered-run-
      labels:
        tekton.dev/pipeline: petclinic-dev-pipeline-tomcat-workspace
    spec:
      pipelineRef:
        name: petclinic-dev-pipeline-tomcat-workspace
      params:
      - name: GIT_REPO
        value: $(params.gitrepositoryurl)
      - name: GIT_REVISION
        value: $(params.gitrevision)
      - name: GIT_MESSAGE
        value: $(params.message)
      resources:
      - name: app-image
        resourceRef:
          name: petclinic-image
      workspaces:
      - name: local-maven-source
        persistentVolumeClaim:
          claimName: maven-source-pvc
      - name: local-maven-repo
        persistentVolumeClaim:
          claimName: maven-repo-pvc