apiVersion: v1
kind: ConfigMap
metadata:
  name: slack-message-payload
data:
  message-payload.json: |
    {
        "text": "Tekton build has completed",
        "blocks": [
            {
                "type": "section",
                "block_id": "section567",
                "text": {
                    "type": "mrkdwn",
                    "text": "<${BUILD_LOGS_URL}|Build ${BUILD_NUM}> has completed :yay:"
                },
                "accessory": {
                    "type": "image",
                    "image_url": "https://user-images.githubusercontent.com/12814972/73849604-22505780-4822-11ea-9fb0-a92fa185ee2a.png",
                    "alt_text": "Tekton Triggers"
                }
            },
            {
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {
                            "type": "plain_text",
                            "text": "Click to promote to staging",
                            "emoji": false
                        },
                        "value" : "${CALLBACK_PAYLOAD}",
                        "url" : "${CALLBACK_URL}"
                    }
                ]
            }
        ]
    }