apiVersion: gpte.opentlc.com/v1alpha1
kind: Gitea
metadata:
  name: gitea-server
spec:
  postgresqlVolumeSize: 1Gi
  giteaVolumeSize: 1Gi
  giteaSsl: True
  giteaServiceName: gitea
  # if these two lines are not provided then the "latest" of the gitea 
  # image will be used and as of 7-12-2020 v1.13.0 was causing a problem with this demo
  giteaImage: "quay.io/gpte-devops-automation/gitea"
  giteaImageTag: "1.12.6"