apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gitea-operator
  template:
    metadata:
      labels:
        name: gitea-operator
    spec:
      serviceAccountName: gitea-operator
      containers:
        - name: gitea-operator
          image: quay.io/gpte-devops-automation/gitea-operator:v0.17
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "gitea-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}